basic/models/User.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $auth_key
 * @property string $access_token
 * @property string $name
 * @property string $date_register
 * @property string $status
 * @property integer $admin
 */
class User extends \yii\db\ActiveRecord
{
    const ROLE_ADMIN = 1;
    const ROLE_USER = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_register'], 'safe'],
            [['status'], 'string'],
            ['username', 'required'],

            [
                ['username', 'email'],
                'unique',
                'on' => 'create'
            ],
            [
                ['username', 'email'],
                'unique',
                'when' => function ($model, $attribute)
                {
                    return $model->{$attribute} !== $model->getOldAttribute($attribute);
                },
                'on' => 'update'
            ],

//            [['username', 'email'], 'unique'],
            [['username'], 'string', 'max' => 20],
            [['password', 'auth_key', 'access_token'], 'string', 'max' => 32],
            ['password', 'required'],
            [['name'], 'string', 'max' => 255],
            ['name', 'required'],
            ['status', 'required'],
            ['email', 'email'],
            ['admin', 'integer'],
            ['group_id', 'integer'],
            ['sort_order', 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Имя пользователя',
            'password' => 'Пароль',
            'auth_key' => 'Auth Key',
            'access_token' => 'Access Token',
            'name' => 'Название ОИВ',
            'date_register' => 'Дата регистрации',
            'email' => 'E-mail',
            'group_id' => 'Группа',
            'status' => 'Статус',
            'admin' => 'Роль',
            'userGroup.title' => 'Группа',
            'sort_order' => 'Порядок сортировки'
        ];
    }

    public function getOldAttribute($name)
    {
        return parent::getOldAttribute($name); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserGroup()
    {
        return $this->hasOne(UserGroup::className(), ['id' => 'group_id']);
    }
}

basic/controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\bootstrap\ActiveForm;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete', 'view'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'create', 'update', 'delete', 'view'],
                        'roles' => ['@'],
                        'matchCallback' => function ()
                        {
                            $userId = Yii::$app->user->id;
                            $userRole = Yii::$app->user->identity->findIdentity($userId)->admin;
//                            $userRole = Yii::$app->user->admin;
                            return $userRole === User::ROLE_ADMIN;
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = -1;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
//        $model = new User(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post()))
        {
            $model->password = $this->hashPassword($model->password);
            $dateRegister = date('Y-m-d H:i:s');
            $model->date_register = $dateRegister;
            if (!$model->admin)
            {
                $model->admin = User::ROLE_USER;
            }
            //return $this->redirect(['view', 'id' => $model->id]);
            if ($model->save())
            {
                echo 1;
            } else
            {
                echo 0;
            }
        } else
        {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionValidationCreate()
    {
        $model = new User;
        $model->scenario = 'create';

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()))
        {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }
    }

    public function actionValidationUpdate($id)
    {
        $model = User::findOne($id);
        $model->scenario = "update";

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post()))
        {
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()))
        {
            if ($model->password != $this->findModel($id)->password)
            {
                $model->password = $this->hashPassword($model->password);
            }
            $model->save();
//            return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else
        {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function hashPassword($password)
    {
        return md5(sha1($password));
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null)
        {
            return $model;
        } else
        {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


}

basic/views/user/_formCreate.php
<?php

use app\models\UserGroup;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

    <div class="user-form">

        <?php $form = ActiveForm::begin([
            'id' => $model->formName(),
            'enableAjaxValidation' => true,
            'validationUrl' => Url::toRoute('user/validation-create')
        ]); ?>

        <?= $form->field($model, 'username')->textInput(['maxlength' => true])->label('Имя пользователя') ?>

        <?= $form->field($model, 'password')->passwordInput(['maxlength' => true])->label('Пароль') ?>

        <!--    --><? //= $form->field($model, 'auth_key')->textInput(['maxlength' => true]) ?>

        <!--    --><? //= $form->field($model, 'access_token')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true])->label('Название ОИВ') ?>
        <?= $form->field($model, 'email')->textInput(['maxlength' => true])->label('E-mail') ?>

        <?= $form->field($model, 'group_id')->dropDownList(
            ArrayHelper::map(UserGroup::find()->all(), 'id', 'title'),
            ['prompt' => 'Выберите группу']
        ) ?>

        <!--    --><? //= $form->field($model, 'date_register')->textInput() ?>

        <?= $form->field($model, 'status')->dropDownList(['active' => 'Активный', 'inactive' => 'Деактивиров',], ['prompt' => 'Выберите статус'])->label('Статус') ?>

        <?= $form->field($model, 'admin')->dropDownList(['1' => 'Админ', '0' => 'Пользователь',], ['prompt' => 'Выберите роль'])->label('Роль пользователя') ?>
        
        <?= $form->field($model, 'sort_order')->textInput(['maxlength' => true])->label('Порядок сортировки') ?>
        
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

<?php $script = <<< JS

$('form#{$model->formName()}').on('beforeSubmit', function(e)
{
    var \$form = $(this);
    $.post(
        \$form.attr("action"), //serialize Yii2 form
        \$form.serialize()
    )
        .done(function(result) {

        if(result == 1)
        {
            //$(\$form).trigger("reset");
            $(document).find('#modal').modal('hide');
            $.pjax.reload({container:'#usersGrid'});
        } else
        {
            $("#message").html(result);
        }
        }).fail(function()
        {
            console.log("server error");
        });
        return false;
});

JS;

$this->registerJs($script);
?>

basic/views/user/_formUpdate.php
<?php

use app\models\UserGroup;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

    <div class="user-form">

        <?php $form = ActiveForm::begin([
            'id' => $model->formName(),
            'enableAjaxValidation' => true,
            'validationUrl' => Url::toRoute('user/validation-update?id=' . $model->id)
        ]); ?>

        <?//= $form->field($model, 'username')->textInput(['maxlength' => true])->label('Имя пользователя') ?>

        <?= $form->field($model, 'password')->passwordInput(['maxlength' => true])->label('Пароль') ?>

        <!--    --><? //= $form->field($model, 'auth_key')->textInput(['maxlength' => true]) ?>

        <!--    --><? //= $form->field($model, 'access_token')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'name')->textInput(['maxlength' => true])->label('Название ОИВ') ?>
        <?= $form->field($model, 'email')->textInput(['maxlength' => true])->label('E-mail') ?>

        <?= $form->field($model, 'group_id')->dropDownList(
            ArrayHelper::map(UserGroup::find()->all(), 'id', 'title'),
            ['prompt' => 'Выберите группу']
        ) ?>

        <!--    --><? //= $form->field($model, 'date_register')->textInput() ?>

        <?= $form->field($model, 'status')->dropDownList(['active' => 'Активный', 'inactive' => 'Деактивиров',], ['prompt' => 'Выберите статус'])->label('Статус') ?>

        <?= $form->field($model, 'admin')->dropDownList(['1' => 'Админ', '0' => 'Пользователь',], ['prompt' => 'Выберите роль'])->label('Роль пользователя') ?>

        <?= $form->field($model, 'sort_order')->textInput(['maxlength' => true])->label('Порядок сортировки') ?>
        
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Изменить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

<?php $script = <<< JS

$('form#{$model->formName()}').on('beforeSubmit', function(e)
{
    var \$form = $(this);
    $.post(
        \$form.attr("action"), //serialize Yii2 form
        \$form.serialize()
    )
        .done(function(result) {

        if(result == 1)
        {
            //$(\$form).trigger("reset");
            $(document).find('#modal').modal('hide');
            $.pjax.reload({container:'#usersGrid'});
        } else
        {
            $("#message").html(result);
        }
        }).fail(function()
        {
            console.log("server error");
        });
        return false;
});

JS;

$this->registerJs($script);
?>

basic/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'globalSearch')->label('Поиск по пользователям') ?>

    <!--    --><? //= $form->field($model, 'username') ?>
    <!---->
    <!--    --><? //= $form->field($model, 'password') ?>
    <!---->
    <!--    --><? //= $form->field($model, 'auth_key') ?>
    <!---->
    <!--    --><? //= $form->field($model, 'access_token') ?>

    <?php // echo $form->field($model, 'name') ?>

    <?php // echo $form->field($model, 'date_register') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?//= Html::resetButton('Сбросить', ['class' => 'btn btn-default',]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Добавление нового пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formCreate', [
        'model' => $model,
    ]) ?>

</div>

basic/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::button('Добавить пользователя', ['value' => Url::to('/user/create'), 'class' => 'btn btn-success', 'id' => 'modalButton']) ?>
    </p>

    <?php
    Modal::begin([
        'header' => '<h4>Пользователи</h4>',
        'id' => 'modal',
        'size' => 'modal-lg',
    ]);
    echo "<div id='modalContent'></div>";
    Modal::end();
    ?>

    <?php Pjax::begin(['id'=>'usersGrid']); ?>
    <?= GridView::widget(['dataProvider' => $dataProvider,
//        'filterModel' => $searchModel,
        'rowOptions' => function ($model)
        {
            if ($model->status == 'inactive')
            {
                return ['class' => 'danger'];
            } else {
                return ['class' => 'success'];
            }
        },
        'columns' => [['class' => 'yii\grid\SerialColumn'],

            //'id',
            'username',
            'password',
            //'auth_key',
            //'access_token',
            'name',
            'date_register',
            'email',
            'status',
            'admin',
            //'group_id',
            //'userGroup.title',
            [
                'attribute' => 'group_id',
                'value' => 'userGroup.title',
            ],
            'sort_order',
            ['class' => 'yii\grid\ActionColumn'],],]); ?>
    <?php Pjax::end(); ?>
</div>

basic/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Изменить пользователя: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменить';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formUpdate', [
        'model' => $model,
    ]) ?>

</div>

basic/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'password',
            'auth_key',
            'access_token',
            'name',
            'date_register',
            'email',
            //'status',
            'admin',
            'userGroup.title',
            'sort_order',
        ],
    ]) ?>

</div>